### ISSUE TITLE
【学習】データ同士の連携

### ISSUE THREAD

**Issue by rkdora** [kyutech-programming-club/monaca-study#1]
# 連携先（ポインタ）の情報を引き出したい

## 現在できること
- ポインタによるデータの連携

## 実現したいこと
- 連携した先のデータをポインタを辿って取得する

## 参考
https://mbaas.nifcloud.com/doc/current/datastore/basic_usage_monaca.html

**Comment by tanacchi** [comment]
User, Element, Language とかは個々のテーブルで管理して，紐付けは id を経由してやれば終わりだと思う

**Comment by tanacchi** [comment]
解決しちゃったから閉じちゃうぜ
